services:
  - type: web
    name: streamlit-app
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
